{% set version = "0.5.0" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: da52e3fc24794e7a45d6ce332201f7144a4c573441cb7554536e6c2544380d2a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bokeh >=1.0
    - colorcet
    - holoviews >=1.11.0
    - pandas

test:
  imports:
    - hvplot
    - hvplot.pandas
    - hvplot.tests

about:
  home: https://pyviz.github.io/hvplot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews
  dev_url: https://github.com/pyviz/hvplot

extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
