{% set version = "0.11.2" %}
{% set python_min = "3.10" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: b7ad1f2f1c705e47e26b22c89c11711a84f7774faaabab756b45e8d1e00a6010

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=30.3.0
    - setuptools_scm >=6
  run:
    - python >={{ python_min }}
    - bokeh >=3.1
    - colorcet >=2
    - holoviews >=1.19.0
    - numpy >=1.21
    - packaging
    - pandas >=1.3
    - panel >=1.0
    - param >=1.12.0,<3.0

test:
  source_files:
    - hvplot
  files:
    - pytest.ini
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
    - pytest hvplot
  requires:
    - pytest
    - pip
    - parameterized
    - xarray
    - pooch
    - netcdf4
    - matplotlib
    - plotly
    - scipy
    - ipywidgets
    - dask
    - bokeh_sampledata   # [py>39]
    - spatialpandas
    - duckdb
    - python {{ python_min }}

about:
  home: https://hvplot.holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews

extra:
  recipe-maintainers:
    - hoxbro
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
    - maximlt
