{% set version = "0.7.0" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: 1c709bebb737ebd71a0433f2333ed15f03dd3c431d4646c41c2b9fcbae4a29b7

build:
  number: 0
  noarch: python
  # ModuleNotFoundError: No module named 'hvplot.__main__'
  # entry_points:
  #   - hvplot = hvplot.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pyct
    - pip
  run:
    - python
    - bokeh >=1.0.0
    - colorcet >=2
    - holoviews >=1.11.0
    - numpy >=1.15
    - pandas

test:
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pyviz.github.io/hvplot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews

extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
