{% set version = "0.4.0" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: bce169cf2d1b3ff9ce607d1787f608758e72a498434eaa2bece31eea1f51963a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bokeh >=1.0
    - holoviews >=1.11.2
    - pandas

test:
  imports:
    - hvplot
    - hvplot.examples
    - hvplot.examples.assets
    - hvplot.examples.user_guide
    - hvplot.examples.user_guide.images
    - hvplot.tests

about:
  home: https://pyviz.github.io/hvplot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews

extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
