{% set version = "0.11.0" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: f3bf7a1dd585e4fda3e97854531c43fb920157b2c500b9e63dd36401ffe28034

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=30.3.0
    - setuptools_scm >=6
  run:
    - python >=3.9
    - bokeh >=3.1
    - colorcet >=2
    - holoviews >=1.19.0
    - numpy >=1.21
    - packaging
    - pandas >=1.3
    - panel >=1.0
    - param >=1.12.0,<3.0

test:
  source_files:
    - hvplot
  files:
    - pytest.ini
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
    - pytest hvplot -k 'not test_explorer_geo_revise_kind'
  requires:
    - pytest
    - pip
    - parameterized
    - xarray
    - pooch
    - netcdf4
    - matplotlib
    - plotly
    - scipy
    - ipywidgets
    - dask
    - bokeh_sampledata   # [py>39]
    - spatialpandas
    - duckdb

about:
  home: https://hvplot.holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews

extra:
  recipe-maintainers:
    - hoxbro
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
    - maximlt
