{% set version = "0.8.2" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: feadb395ac01a0be5fc89155452446c2b9c412a99d63eac029083138163d5c1b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - param >=1.7.0
    - pip
    - pyct >=0.4.4
    - setuptools >=30.3.0
  run:
    - python >=3.6
    - bokeh >=1.0.0
    - colorcet >=2
    - holoviews >=1.11.0
    - numpy >=1.15
    - packaging
    - pandas

test:
  source_files:
    - hvplot
  files:
    - pytest.ini
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
    - pytest hvplot -k "not test_urls[core.py]"
  requires:
    - pip
    - pytest
    - parameterized
    - xarray
    - pooch
    - netcdf4
    - plotly

about:
  home: https://hvplot.holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews

extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
    - maximlt
