# Global pin is 3.9 now, we're ahead so pin it here.
{% set python_min = "3.10" %}
{% set version = "0.12.1" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: 66f4c9dbb7e5580c09ade55b14864ff6fcc96ed9ce11f7b67e9eb7072e2ed875

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.25.0
    - hatch-vcs >=0.4.0
  run:
    - python >={{ python_min }}
    - bokeh >=3.1
    - colorcet >=2
    - holoviews >=1.19.0
    - numpy >=1.21
    - packaging
    - pandas >=1.3
    - panel >=1.0
    - param >=1.12.0,<3.0

test:
  source_files:
    - hvplot
  files:
    - pytest.ini
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
    - pytest hvplot
  requires:
    - python {{ python_min }}
    - pytest
    - pip
    - parameterized
    - xarray
    - pooch
    - netcdf4
    - matplotlib
    - plotly
    - scipy
    - ipywidgets
    - dask
    - bokeh_sampledata   # [py>=310]
    - spatialpandas
    - duckdb

about:
  home: https://hvplot.holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews

extra:
  recipe-maintainers:
    - hoxbro
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
    - maximlt
