{% set version = "0.8.0" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: 8630dba34969b105e267cbe14237e2d56d9969c801980ae5e5190bc18b2792d6

build:
  number: 0
  noarch: python
  # ModuleNotFoundError: No module named 'hvplot.__main__'
  # entry_points:
  #   - hvplot = hvplot.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pyct
    - pip
  run:
    - python >=3.6
    - packaging
    - param >=1.12.0
    - bokeh >=2.0.0
    - colorcet >=2
    - holoviews >=1.12.0
    - numpy >=1.15
    - pandas

test:
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hvplot.holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews

extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
    - maximlt
