{% set version = "0.9.2" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: 9a8c9e9249139aaa3dee5f1cea0f93cf36374d179e986705fcddc2b92c470793

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - param >=1.7.0
    - pip
    - pyct >=0.4.4
    - setuptools >=30.3.0
  run:
    - python >=3.8
    - bokeh >=1.0.0
    - colorcet >=2
    - holoviews >=1.11.0
    - numpy >=1.15
    - packaging
    - pandas
    - panel >=0.11.0
    - param >=1.12.0,<3.0

test:
  source_files:
    - hvplot
  files:
    - pytest.ini
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
    - pytest hvplot
  requires:
    - pytest
    - pip
    - parameterized
    - xarray
    - pooch
    - netcdf4
    - matplotlib
    - plotly
    - scipy
    - ipywidgets
    - dask

about:
  home: https://hvplot.holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews

extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
    - maximlt
